### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by wjzlyr** [nicklly/nonebot_plugin_StarRail_calendar#6]
使用nb安装的时候报错
![1](https://github.com/nicklly/nonebot_plugin_StarRail_calendar/assets/58624426/66c44ba5-ede2-4c99-b218-dd4625abb619)
![2](https://github.com/nicklly/nonebot_plugin_StarRail_calendar/assets/58624426/ebee438c-5a68-4084-9589-ed783bde2772)
![Uploading 3.png…]()

**Comment by nicklly** [comment]
直接使用nb plugin install nonebot-plugin-starrail-calendar呢
