### ISSUE TITLE
Bug:获取的ctime缺少默认值

### ISSUE THREAD

**Issue by Pythagoras-Euler** [nicklly/nonebot_plugin_StarRail_calendar#8]
初次运行时，插件出现报错：ctime未绑定值。
![6336e576db9f1587363dd76b5c50e8a7](https://github.com/nicklly/nonebot_plugin_StarRail_calendar/assets/90089309/acaded56-e8ad-4dd7-a8c9-b887c4f88b41)
查看代码后，推测ctime所在try-catch函数异常跳出
![f5de3c139637d9175d124094d6f1d661](https://github.com/nicklly/nonebot_plugin_StarRail_calendar/assets/90089309/a1d95cda-c9eb-4b8d-a67c-ad83f887ba3d)
在catch函数内给ctime赋予默认时间值之后，代码正常运行，开始下载chromium核心。

**Comment by nicklly** [comment]
> 初次运行时，插件出现报错：ctime未绑定值。
> ![6336e576db9f1587363dd76b5c50e8a7](https://github.com/nicklly/nonebot_plugin_StarRail_calendar/assets/90089309/acaded56-e8ad-4dd7-a8c9-b887c4f88b41)
> 查看代码后，推测ctime所在try-catch函数异常跳出
> ![f5de3c139637d9175d124094d6f1d661](https://github.com/nicklly/nonebot_plugin_StarRail_calendar/assets/90089309/a1d95cda-c9eb-4b8d-a67c-ad83f887ba3d)
> 在catch函数内给ctime赋予默认时间值之后，代码正常运行，开始下载chromium核心。
> 

并没有默认值，ctime变量是用来汽配活动时间的

**Comment by Pythagoras-Euler** [comment]
是不是有一个死锁的问题：初次运行时，电脑内没有chromium相关环境，代码运行到这里获取不到时间就会报错退出，然后也不会自动下载相关环境。只要我们暂时的在这里赋一个假值，代码就能走到后面安装调用依赖的部分，跑通整段程序。

**Comment by nicklly** [comment]
> 是不是有一个死锁的问题：初次运行时，电脑内没有chromium相关环境，代码运行到这里获取不到时间就会报错退出，然后也不会自动下载相关环境。只要我们暂时的在这里赋一个假值，代码就能走到后面安装调用依赖的部分，跑通整段程序。

不影响的，如果没有安装playwright，报错就不会是这个了，晚上我更新一下你再尝试一下吧

**Comment by mengluo04** [comment]
> > 是不是有一个死锁的问题：初次运行时，电脑内没有chromium相关环境，代码运行到这里获取不到时间就会报错退出，然后也不会自动下载相关环境。只要我们暂时的在这里赋一个假值，代码就能走到后面安装调用依赖的部分，跑通整段程序。
> 
> 不影响的，如果没有安装playwright，报错就不会是这个了，晚上我更新一下你再尝试一下吧

现在还是报这个错：
![image](https://github.com/nicklly/nonebot_plugin_StarRail_calendar/assets/32565940/6c618c75-9a7c-4648-b58f-425b87cfd65c)

**Comment by nicklly** [comment]
> > > 是不是有一个死锁的问题：初次运行时，电脑内没有chromium相关环境，代码运行到这里获取不到时间就会报错退出，然后也不会自动下载相关环境。只要我们暂时的在这里赋一个假值，代码就能走到后面安装调用依赖的部分，跑通整段程序。
> > 
> > 
> > 不影响的，如果没有安装playwright，报错就不会是这个了，晚上我更新一下你再尝试一下吧
> 
> 现在还是报这个错： ![image](https://private-user-images.githubusercontent.com/32565940/337975546-6c618c75-9a7c-4648-b58f-425b87cfd65c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5Mzg2OTEsIm5iZiI6MTcxNzkzODM5MSwicGF0aCI6Ii8zMjU2NTk0MC8zMzc5NzU1NDYtNmM2MThjNzUtOWE3Yy00NjQ4LWI1OGYtNDI1Yjg3Y2ZkNjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEzMDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNmFlOGY2MzMxZDFkNTNmNjJmYWJjNTQ0NWQxMWY1ZmI3NmU0N2NhYjNmZjNkZmMwMjkxOWM0NDhmMGExOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sVy8LiQlU4dU9lcex72rQ2qvI96yi__lZDOitQLkJqQ)

私密马赛 我忘记更新了qwq

**Comment by nicklly** [comment]
已经推送了更新，不妨试试看.jpg

**Comment by mengluo04** [comment]
> 已经推送了更新，不妨试试看.jpg

pypi上还没更新

**Comment by nicklly** [comment]
> > 已经推送了更新，不妨试试看.jpg
> 
> pypi上还没更新

emm 可以的话请直接从github更新吧

**Comment by mengluo04** [comment]
> > > 已经推送了更新，不妨试试看.jpg
> > 
> > 
> > pypi上还没更新
> 
> emm 可以的话请直接从github更新吧

从源码安装是把源码里的nonebot_plugin_starrail_calendar目录放到插件目录吧，启动报错了
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/__init__.py", line 15, in <module>
    from .draw_calendar import *
  File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/draw_calendar.py", line 4, in <module>
    from .data_source import *
  File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/data_source.py", line 10, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'

**Comment by nicklly** [comment]
> > > > 已经推送了更新，不妨试试看.jpg
> > > 
> > > 
> > > pypi上还没更新
> > 
> > 
> > emm 可以的话请直接从github更新吧
> 
> 从源码安装是把源码里的nonebot_plugin_starrail_calendar目录放到插件目录吧，启动报错了 Traceback (most recent call last): File "", line 16, in File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins return manager.load_all_plugins() File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins return set( File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> 
> > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
> > module = importlib.import_module(self._searched_plugin_ids[name])
> > File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1050, in _gcd_import
> > File "", line 1027, in _find_and_load
> > File "", line 1006, in _find_and_load_unlocked
> > File "", line 688, in _load_unlocked
> > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
> > super().exec_module(module)
> > File "", line 883, in exec_module
> > File "", line 241, in _call_with_frames_removed
> > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/**init**.py", line 15, in 
> > from .draw_calendar import *
> > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/draw_calendar.py", line 4, in 
> > from .data_source import *
> > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/data_source.py", line 10, in 
> > from dateutil.relativedelta import relativedelta
> > ModuleNotFoundError: No module named 'dateutil'

这是缺少了库啊xd 你检查下site-packages里有没dateutil这个库

**Comment by mengluo04** [comment]
> > > > > 已经推送了更新，不妨试试看.jpg
> > > > 
> > > > 
> > > > pypi上还没更新
> > > 
> > > 
> > > emm 可以的话请直接从github更新吧
> > 
> > 
> > 从源码安装是把源码里的nonebot_plugin_starrail_calendar目录放到插件目录吧，启动报错了 Traceback (most recent call last): File "", line 16, in File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins return manager.load_all_plugins() File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins return set( File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
> > > module = importlib.import_module(self._searched_plugin_ids[name])
> > > File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module
> > > return _bootstrap._gcd_import(name[level:], package, level)
> > > File "", line 1050, in _gcd_import
> > > File "", line 1027, in _find_and_load
> > > File "", line 1006, in _find_and_load_unlocked
> > > File "", line 688, in _load_unlocked
> > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
> > > super().exec_module(module)
> > > File "", line 883, in exec_module
> > > File "", line 241, in _call_with_frames_removed
> > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/**init**.py", line 15, in
> > > from .draw_calendar import *
> > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/draw_calendar.py", line 4, in
> > > from .data_source import *
> > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/data_source.py", line 10, in
> > > from dateutil.relativedelta import relativedelta
> > > ModuleNotFoundError: No module named 'dateutil'
> 
> 这是缺少了库啊xd 你检查下site-packages里有没dateutil这个库

这就是源码安装的不方便，没有requirements，都不知道要啥依赖，不会自动安装

**Comment by nicklly** [comment]
> > > > > > 已经推送了更新，不妨试试看.jpg
> > > > > 
> > > > > 
> > > > > pypi上还没更新
> > > > 
> > > > 
> > > > emm 可以的话请直接从github更新吧
> > > 
> > > 
> > > 从源码安装是把源码里的nonebot_plugin_starrail_calendar目录放到插件目录吧，启动报错了 Traceback (most recent call last): File "", line 16, in File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins return manager.load_all_plugins() File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins return set( File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
> > > > module = importlib.import_module(self._searched_plugin_ids[name])
> > > > File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module
> > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > File "", line 1050, in _gcd_import
> > > > File "", line 1027, in _find_and_load
> > > > File "", line 1006, in _find_and_load_unlocked
> > > > File "", line 688, in _load_unlocked
> > > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
> > > > super().exec_module(module)
> > > > File "", line 883, in exec_module
> > > > File "", line 241, in _call_with_frames_removed
> > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/**init**.py", line 15, in
> > > > from .draw_calendar import *
> > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/draw_calendar.py", line 4, in
> > > > from .data_source import *
> > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/data_source.py", line 10, in
> > > > from dateutil.relativedelta import relativedelta
> > > > ModuleNotFoundError: No module named 'dateutil'
> > 
> > 
> > 这是缺少了库啊xd 你检查下site-packages里有没dateutil这个库
> 
> 这就是源码安装的不方便，没有requirements，都不知道要啥依赖，不会自动安装

行吧.jpg 今晚回去更新下pypi的（我这是想偷懒都不行T_T）

**Comment by mengluo04** [comment]
> > > > > > > 已经推送了更新，不妨试试看.jpg
> > > > > > 
> > > > > > 
> > > > > > pypi上还没更新
> > > > > 
> > > > > 
> > > > > emm 可以的话请直接从github更新吧
> > > > 
> > > > 
> > > > 从源码安装是把源码里的nonebot_plugin_starrail_calendar目录放到插件目录吧，启动报错了 Traceback (most recent call last): File "", line 16, in File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins return manager.load_all_plugins() File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins return set( File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
> > > > > module = importlib.import_module(self._searched_plugin_ids[name])
> > > > > File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module
> > > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > > File "", line 1050, in _gcd_import
> > > > > File "", line 1027, in _find_and_load
> > > > > File "", line 1006, in _find_and_load_unlocked
> > > > > File "", line 688, in _load_unlocked
> > > > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
> > > > > super().exec_module(module)
> > > > > File "", line 883, in exec_module
> > > > > File "", line 241, in _call_with_frames_removed
> > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/**init**.py", line 15, in
> > > > > from .draw_calendar import *
> > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/draw_calendar.py", line 4, in
> > > > > from .data_source import *
> > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/data_source.py", line 10, in
> > > > > from dateutil.relativedelta import relativedelta
> > > > > ModuleNotFoundError: No module named 'dateutil'
> > > 
> > > 
> > > 这是缺少了库啊xd 你检查下site-packages里有没dateutil这个库
> > 
> > 
> > 这就是源码安装的不方便，没有requirements，都不知道要啥依赖，不会自动安装
> 
> 行吧.jpg 今晚回去更新下pypi的（我这是想偷懒都不行T_T）

已经搞定了（

**Comment by nicklly** [comment]
> > > > > > > > 已经推送了更新，不妨试试看.jpg
> > > > > > > 
> > > > > > > 
> > > > > > > pypi上还没更新
> > > > > > 
> > > > > > 
> > > > > > emm 可以的话请直接从github更新吧
> > > > > 
> > > > > 
> > > > > 从源码安装是把源码里的nonebot_plugin_starrail_calendar目录放到插件目录吧，启动报错了 Traceback (most recent call last): File "", line 16, in File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins return manager.load_all_plugins() File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins return set( File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > > > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
> > > > > > module = importlib.import_module(self._searched_plugin_ids[name])
> > > > > > File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module
> > > > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > > > File "", line 1050, in _gcd_import
> > > > > > File "", line 1027, in _find_and_load
> > > > > > File "", line 1006, in _find_and_load_unlocked
> > > > > > File "", line 688, in _load_unlocked
> > > > > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
> > > > > > super().exec_module(module)
> > > > > > File "", line 883, in exec_module
> > > > > > File "", line 241, in _call_with_frames_removed
> > > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/**init**.py", line 15, in
> > > > > > from .draw_calendar import *
> > > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/draw_calendar.py", line 4, in
> > > > > > from .data_source import *
> > > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/data_source.py", line 10, in
> > > > > > from dateutil.relativedelta import relativedelta
> > > > > > ModuleNotFoundError: No module named 'dateutil'
> > > > 
> > > > 
> > > > 这是缺少了库啊xd 你检查下site-packages里有没dateutil这个库
> > > 
> > > 
> > > 这就是源码安装的不方便，没有requirements，都不知道要啥依赖，不会自动安装
> > 
> > 
> > 行吧.jpg 今晚回去更新下pypi的（我这是想偷懒都不行T_T）
> 
> 已经搞定了（

草草草 行动力max了属于是🤣👉👍

**Comment by mengluo04** [comment]
> > > > > > > > > 已经推送了更新，不妨试试看.jpg
> > > > > > > > 
> > > > > > > > 
> > > > > > > > pypi上还没更新
> > > > > > > 
> > > > > > > 
> > > > > > > emm 可以的话请直接从github更新吧
> > > > > > 
> > > > > > 
> > > > > > 从源码安装是把源码里的nonebot_plugin_starrail_calendar目录放到插件目录吧，启动报错了 Traceback (most recent call last): File "", line 16, in File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins return manager.load_all_plugins() File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins return set( File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > > > > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
> > > > > > > module = importlib.import_module(self._searched_plugin_ids[name])
> > > > > > > File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module
> > > > > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > > > > File "", line 1050, in _gcd_import
> > > > > > > File "", line 1027, in _find_and_load
> > > > > > > File "", line 1006, in _find_and_load_unlocked
> > > > > > > File "", line 688, in _load_unlocked
> > > > > > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
> > > > > > > super().exec_module(module)
> > > > > > > File "", line 883, in exec_module
> > > > > > > File "", line 241, in _call_with_frames_removed
> > > > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/**init**.py", line 15, in
> > > > > > > from .draw_calendar import *
> > > > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/draw_calendar.py", line 4, in
> > > > > > > from .data_source import *
> > > > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/data_source.py", line 10, in
> > > > > > > from dateutil.relativedelta import relativedelta
> > > > > > > ModuleNotFoundError: No module named 'dateutil'
> > > > > 
> > > > > 
> > > > > 这是缺少了库啊xd 你检查下site-packages里有没dateutil这个库
> > > > 
> > > > 
> > > > 这就是源码安装的不方便，没有requirements，都不知道要啥依赖，不会自动安装
> > > 
> > > 
> > > 行吧.jpg 今晚回去更新下pypi的（我这是想偷懒都不行T_T）
> > 
> > 
> > 已经搞定了（
> 
> 草草草 行动力max了属于是🤣👉👍

不涉及代码逻辑，不需要动脑子（，顺便把firefox改成chromium了

**Comment by nicklly** [comment]
> > > > > > > > > > 已经推送了更新，不妨试试看.jpg
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > pypi上还没更新
> > > > > > > > 
> > > > > > > > 
> > > > > > > > emm 可以的话请直接从github更新吧
> > > > > > > 
> > > > > > > 
> > > > > > > 从源码安装是把源码里的nonebot_plugin_starrail_calendar目录放到插件目录吧，启动报错了 Traceback (most recent call last): File "", line 16, in File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins return manager.load_all_plugins() File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins return set( File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > > > > > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
> > > > > > > > module = importlib.import_module(self._searched_plugin_ids[name])
> > > > > > > > File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module
> > > > > > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > > > > > File "", line 1050, in _gcd_import
> > > > > > > > File "", line 1027, in _find_and_load
> > > > > > > > File "", line 1006, in _find_and_load_unlocked
> > > > > > > > File "", line 688, in _load_unlocked
> > > > > > > > File "/home/software/nb-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
> > > > > > > > super().exec_module(module)
> > > > > > > > File "", line 883, in exec_module
> > > > > > > > File "", line 241, in _call_with_frames_removed
> > > > > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/**init**.py", line 15, in
> > > > > > > > from .draw_calendar import *
> > > > > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/draw_calendar.py", line 4, in
> > > > > > > > from .data_source import *
> > > > > > > > File "/home/software/nb-bot/plugins/nonebot_plugin_starrail_calendar/data_source.py", line 10, in
> > > > > > > > from dateutil.relativedelta import relativedelta
> > > > > > > > ModuleNotFoundError: No module named 'dateutil'
> > > > > > 
> > > > > > 
> > > > > > 这是缺少了库啊xd 你检查下site-packages里有没dateutil这个库
> > > > > 
> > > > > 
> > > > > 这就是源码安装的不方便，没有requirements，都不知道要啥依赖，不会自动安装
> > > > 
> > > > 
> > > > 行吧.jpg 今晚回去更新下pypi的（我这是想偷懒都不行T_T）
> > > 
> > > 
> > > 已经搞定了（
> > 
> > 
> > 草草草 行动力max了属于是🤣👉👍
> 
> 不涉及代码逻辑，不需要动脑子（，顺便把firefox改成chromium了

ok 如果没其他问题的话那我就关issue了（）
